[project]
name = "pytnl-docs"
version = "0.1.0"

dependencies = ["mkdocs", "mkdocs-material"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.pyright]
exclude = [".venc", "build"]
